### PR TITLE
Fix the lifetime annotation of PointTrait implemented for geo_types::Point

### PR DESCRIPTION
**Pull request by Kontinuation**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/main/CODE_OF_CONDUCT.md).
- [x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

I found this lifetime problem when building layers of generic abstractions over geo-traits and geo-types. The fix makes the lifetime of `CoordType` of `Point` consistent with other types in geo-types.

### CODE REVIEW

**Review by kylebarron — APPROVED** [review]
Thank you! I don't understand lifetimes as well as I should so I'd love to get another's review on this as well.

**Comment by michaelkirk** [comment]
Can you give an example of some code that wouldn't compile before this change which will compile after this change?

**Comment by kylebarron** [comment]
This related PR https://github.com/georust/wkb/pull/59#pullrequestreview-2784245504 has an example for the WKB point object; not sure if it's relevant here too

**Review by frewsxcv — APPROVED** [review]

**Comment by frewsxcv** [comment]
Yep a regression test would be great for this @Kontinuation if you have one.

I think I made this change locally last week to work around an issue with lifetimes but I think I blew away that branch sadly.

**Comment by frewsxcv** [comment]
Also we should consider doing the same for the other geo-types implementations, assuming it's also applicable for them and not just `geo_types::Point`

File: geo-traits/src/point.rs [hunk 1]
```diff
@@ -34,11 +34,11 @@ impl<T: CoordNum> PointTrait for Point<T> {
 }
 
 #[cfg(feature = "geo-types")]
-impl<T: CoordNum> PointTrait for &Point<T> {
-    type CoordType<'a>
+impl<'a, T: CoordNum> PointTrait for &'a Point<T> {
```
Comment (michaelkirk) [inline geo-traits/src/point.rs:37]: I confess, I'm not great with lifetimes, but I feel like this is a no-op change?

Comment (urschrei) [reply geo-traits/src/point.rs:37]: Well if we're all admitting that we're "not that great at lifetimes" I'll chime in and admit it too. I assume that this change is intended to make it clearer that the lifetime of the returned coordinate matches the lifetime of the source reference. But does "clearer" in this case actually mean "fixes a `borrowck` error"? Great if it does, and we'd love to see it – I thought the existing lifetime arrangement already made the relationship clear.

**Comment by Kontinuation** [comment]
> Yep a regression test would be great for this @Kontinuation if you have one.
> 
> I think I made this change locally last week to work around an issue with lifetimes but I think I blew away that branch sadly.

I have added a regression test in https://github.com/georust/geo/pull/1348/commits/8efd199d6f2f782c72a8abb7a7961d7bbb18f1a3, which is a minimal reproducer we can derive from the overly restrictive lifetime annotation. This is not exactly the problem I initially encountered though (it was a trait bound about lifetime constraint), but I think it should be good enough.

Without the fix, the newly added test won't compile:

```
error[E0597]: `point_ref` does not live long enough
  --> geo-traits/src/point.rs:61:47
   |
59 |         let point_ref: &Point<f64> = &point;
   |             --------- binding `point_ref` declared here
60 |         {
61 |             let point_ref_ref: &&Point<f64> = &point_ref;
   |                                               ^^^^^^^^^^ borrowed value does not live long enough
...
66 |     }
   |     - `point_ref` dropped here while still borrowed
...
70 |     assert_eq!(coord_ref.x(), 1.0);
   |                --------- borrow later used here
```

**Comment by frewsxcv** [comment]
@Kontinuation How do you feel about making this change for the other geometry types and not just point? I can do it in a follow-up if you want, or just push to your branch directly

**Comment by Kontinuation** [comment]
> @Kontinuation How do you feel about making this change for the other geometry types and not just point? I can do it in a follow-up if you want, or just push to your branch directly

The lifetime annotations for all other types seems to be correct, do you want me to add tests for all other types?

Another thing amuses me is that the `CoordType` of `Rect` is an owned type instead of reference type, I'm not sure if it is by design.

**Comment by kylebarron** [comment]
> Another thing amuses me is that the `CoordType` of `Rect` is an owned type instead of reference type, I'm not sure if it is by design.

`Rect`, `LineString`, and `Point` all have owned coord types with a lifetime parameter
https://github.com/georust/geo/blob/b0d02de7814ea4ca48312bad4b7e8d11040cce8f/geo-traits/src/point.rs#L12-L16
https://github.com/georust/geo/blob/b0d02de7814ea4ca48312bad4b7e8d11040cce8f/geo-traits/src/line_string.rs#L15-L18
https://github.com/georust/geo/blob/b0d02de7814ea4ca48312bad4b7e8d11040cce8f/geo-traits/src/rect.rs#L13-L16

Or do you mean this distinction
https://github.com/georust/geo/blob/b0d02de7814ea4ca48312bad4b7e8d11040cce8f/geo-traits/src/rect.rs#L27-L28
https://github.com/georust/geo/blob/b0d02de7814ea4ca48312bad4b7e8d11040cce8f/geo-traits/src/point.rs#L26-L27

Given that a `Coord` is `Copy`, indeed it seems better to not have a reference.

File: geo-traits/src/point.rs [hunk 2]
```diff
@@ -34,11 +34,11 @@ impl<T: CoordNum> PointTrait for Point<T> {
...
+    type CoordType<'b>
         = &'a Coord<<Self as GeometryTrait>::T>
```
Comment (michaelkirk) [inline geo-traits/src/point.rs:39]: Ah! This is the line that I missed. The `&'a` here used to refer to the `CoordType<'a>`, but now references the lifetime of the `impl &'a Point`

I see now how this is now more relaxed. Thanks for the test!

**Review by michaelkirk — APPROVED** [review]
